### ISSUE TITLE
Google colab demo is not working with tensorflow 2.6

### ISSUE THREAD

**Issue by arye321** [kingoflolz/mesh-transformer-jax#105] opened 2021-08-19 23:11 UTC
`tokenizer = transformers.GPT2TokenizerFast.from_pretrained('gpt2') `

did not work

`!pip install tensorflow==2.5.0`

fixed for that for me

**Comment by mdnestor** [comment] 2021-08-20 02:06
Duplicate of https://github.com/kingoflolz/mesh-transformer-jax/issues/103

**Closed** 2021-08-21 17:37 UTC
