### ISSUE TITLE
when Try to run using any production wsgi server it gives '_thread._local' object has no attribute 'env'

### ISSUE THREAD

**Issue by ahmedjawedaj** [kingoflolz/mesh-transformer-jax#42] opened 2021-07-08 21:17 UTC
Tried deploying it using 

1. Flask + systemd daemon service
2. building docker example provided

`ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/uvicorn/protocols/http/h11_impl.py", line 369, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.6/dist-packages/uvicorn/middleware/proxy_headers.py", line 59, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.6/dist-packages/fastapi/applications.py", line 201, in __call__
    await super().__call__(scope, receive, send)  # pragma: no cover
  File "/usr/local/lib/python3.6/dist-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.6/dist-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.6/dist-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.6/dist-packages/starlette/middleware/cors.py", line 78, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.6/dist-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.6/dist-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.6/dist-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.6/dist-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.6/dist-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/usr/local/lib/python3.6/dist-packages/fastapi/routing.py", line 217, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/usr/local/lib/python3.6/dist-packages/fastapi/routing.py", line 151, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.6/dist-packages/starlette/concurrency.py", line 40, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/contextvars/__init__.py", line 38, in run
    return callable(*args, **kwargs)
  File "./main.py", line 49, in model_prediction
    re = MODEL_API.infer("what is AI?", length=30)
  File "./ops.py", line 115, in infer
    "temp": np.ones(self.total_batch) * temp,
  File "/app/mesh-transformer-jax/mesh_transformer/transformer_shard.py", line 314, in generate
    sampler_options)
  File "/usr/local/lib/python3.6/dist-packages/jax/experimental/maps.py", line 568, in fun_mapped
    resource_env = thread_resources.env
AttributeError: '_thread._local' object has no attribute 'env'`

**Comment by kingoflolz** [comment] 2021-07-10 21:28
I have not personally tested the docker example and am not able to provide any support, perhaps @trisongz can assist?

**Comment by trisongz** [comment] 2021-07-12 21:31
I recall running into this error, but it seems like you're running it differently than how the original main script has it.
This error rises due to how API libraries create multiple workers and try to load the model while jax has threadlock and mesh-transformer-jax creates assertions that can't be validated:

```
# https://github.com/kingoflolz/mesh-transformer-jax/blob/062de8632922a9fb690db452a83a31aaf653c557/mesh_transformer/transformer_shard.py#L248
assert thread_resources.env.shape['mp'] == config["cores_per_replica"]
```

Since you might be loading the model differently, look at
https://github.com/kingoflolz/mesh-transformer-jax/blob/062de8632922a9fb690db452a83a31aaf653c557/docker/ops.py#L65 to see how I am bypassing that check.

**Comment by ahmedjawedaj** [comment] 2021-07-12 22:15
I am running this example in default way and models are loading fine, Issue is occurring on generating output.
so here's the default flow

`exec uvicorn --reload --reload-dir /app/mesh-transformer-jax --host $HOST --port $PORT --log-level $LOG_LEVEL "$APP_MODULE" --access-log`

It Runs Fast Api server via uvicorn,  it calls Fast startup_event and loads model successfully.
I am then calling MODEL_API.infer("What is AI?", length=50) under model_prediction api endpoint and it's generating this error.

I also tried with default endpoints, `/model/predict` this one  is returning the id, but when i call 2nd endpoint which is `/model/get_prediction` it got stuck and didn't return anything.

That's why i am trying to call `MODEL_API.infer("What is AI?", length=50)` directly under this `/model/predict` endpoint.

**Comment by ahmedjawedaj** [comment] 2021-07-12 22:29
One more thing, I am using 
This `with jax.experimental.maps.mesh(devices, ('dp', 'mp')):` instead of
`maps.thread_resources.env = maps.ResourceEnv(maps.Mesh(self.devices, ('dp', 'mp')))`

It's not working for me on TPU vm without using `with` keyword
with or without docker.

**Comment by trisongz** [comment] 2021-07-13 21:51
Without looking at your code for how the API is modified, I can't tell you what the cause of it is.

The /get_prediction endpoint waits until the prediction is complete, and depending on your accelerator, it could be a while. First prediction on TPU v2-8 takes around 50-60 secs before a result is returned.

The reason that I have it as 
`maps.thread_resources.env = maps.ResourceEnv(maps.Mesh(self.devices, ('dp', 'mp')))`

is so that it patches `jax.experimental.maps.thread_resources` to include the `env` attribute.

**Comment by kingoflolz** [comment] 2021-07-17 06:37
Thanks @trisongz !

@ahmedjawedaj Closing as I'm unable to support the docker implementation, especially if the code has been modified.

**Closed by kingoflolz** 2021-07-17 06:37 UTC
